### ISSUE TITLE
Setpoint not always shown

### ISSUE THREAD

**Issue by clandmeter** [ralfvd/nl.bevlogenheid.evohome#5] opened 2017-01-11 15:51 UTC
Not sure when this happens, but this morning I moved my Homey and after I got to work I could not see the setpoint (see picture). I waited again but the log did not show Homey receiving it. After I changed it via my Vera after around 5 minutes the setpoint appeared again.

![image](https://cloud.githubusercontent.com/assets/52970/21855170/b5d3648e-d81d-11e6-991c-4153817cc7b8.png)

**Comment by ralfvd** [comment] 2017-01-11 20:13
I think this is caused by the reboot of Homey; the app will only record a setpoint (or current temperature) when there is a change. I just rebooted my Homey and indeed, the setpoint is not shown. 

I'll check if it is possible to record the setpoint after a reboot, but not trigger the 'target temperature changed' flows.

As far as I can see all functions will still work, it just doesn't show the current setpoint in the device card.

Thanks for noticing! I'll keep the issue open until it is solved (or confirmed that I cannot fix this)

**Comment by clandmeter** [comment] 2017-02-23 10:20
@ralfvd did you ever find time to fix this issue? I frequently have to restart my homey (Z-wave inclusion/testing) and then the setpoints are all null.

**Comment by ralfvd** [comment] 2019-01-15 12:00
Updating setpoints should now be better in version 2.0.0 ( out in Beta right now), although there is still a delay of updating them. But after a reboot it should have remembered the setpoint settings.

I will close this now, when you are running 2.0 , and it is still an issue, please raise another issue, so I can look into it.

**Closed as completed by ralfvd** 2019-01-15 12:00 UTC
