### ISSUE TITLE
Quik Setting not working & login timout

### ISSUE THREAD

**Issue by mickelluiten** [ralfvd/nl.bevlogenheid.evohome#17] opened 2018-12-18 17:19 UTC
HI,   noticed 2 problems with this app.
Running Homey 1.5.13.

1.  when setting a quik action,  nothing happens.
Run the app in debug mode and the below error messages popups.

Start Session Code: 429
invalid settings
(node:31850) UnhandledPromiseRejectionWarning: ReferenceError: callback is not defined
    at /lib/evohomey.js:155:16
    at /lib/evohomey.js:286:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:31850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
18:03:19 QuickAction:  Custom
91db1612-73fd-4500-91b2-e63b069b185c
Start Session Code: 429
invalid settings
(node:31850) UnhandledPromiseRejectionWarning: ReferenceError: callback is not defined
    at /lib/evohomey.js:155:16
    at /lib/evohomey.js:286:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:31850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

2.  Conncetion Error/Timeouts,    
Looks like there are many requests to the honeywell cloud and the result is timeouts / bad connections
If this happens , the login parameter check on the settings page,  throws back a Incorrect setting messages.
After a while when i try it again its works again.
Something to do with te ratelimiting from honeywell?

**Comment by psy0rz** [comment] 2018-12-19 11:59
can confirm. i changed the debugging output so that it interprets the http return code. It indeed says something like "too many logins, retry again later"

**Comment by psy0rz** [comment] 2018-12-19 12:00
duplicate of #15

**Comment by ralfvd** [comment] 2018-12-22 11:41
This is a result of Honeywell being stricter in amount of logins per hour. And the current code is not efficient in using logins. 

A rewrite will be needed including an update to sdk 2. This will be tracked in other issues so for now I’ll close this one.

**Closed as completed by ralfvd** 2018-12-22 11:41 UTC
