### ISSUE TITLE
Timeout in Homey v 2

### ISSUE THREAD

**Issue by Lansuper** [ralfvd/nl.bevlogenheid.evohome#15] opened 2018-12-12 05:36 UTC
Setting the temperature through a card or the app shows a timeout after 30000 ms but temperature does change on the evohome thermostat. Restarting the app on Homey has no effect.

**Comment by psy0rz** [comment] 2018-12-18 14:26
same here, but it doesnt update the thermostat.

Running in debug mode from cli:
```
Set Device Temperature result: 201
Response: {
  "id": 276938383
}
15:23:59 1537948: new target temperature set: 19.0
(node:1481) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at /drivers/thermostat/driver.js:582:19
    at /lib/evohomey.js:248:9
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:1481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Will try to figure out if i can fix it myself. I already started working on better error handling a while ago.

**Comment by psy0rz** [comment] 2018-12-18 15:02
@ralfvd : When changing the target temperature and the ratelimiter is hit, will it eventually still update the target temperature on the next update?

Also, it seems a lot of errors are caused by previous errors, like the ratelimiter from honeywell.

**Comment by psy0rz** [comment] 2018-12-19 12:15
It seems new Evohomey() is called every time an action is done and a login() is done every time. 

Wouldnt it be possible to keep the Evohomey() instance and store the sessionID, resulting in only one login? (or a login whenever the session has expired)

I also dont undertand why there is http communication stuff directly from driver.js. Shouldn't that be in evohomey.js?

**Comment by ralfvd** [comment] 2018-12-26 09:40
Complete rewrite of login is happening for sdk2. Tracked in issue #17

**Comment by ralfvd** [comment] 2018-12-26 09:42
Progress tracked in issue #18

**Comment by ralfvd** [comment] 2019-01-15 11:57
I am going to close this issue, as SDK2 / Homey 2.0 rewrite is now in beta and tracked in #18

**Closed as completed by ralfvd** 2019-01-15 11:57 UTC
